### ISSUE TITLE
Rename columns to avoid SQL syntax error

### ISSUE THREAD

**Issue by reshmabidikar** [killbill/killbill-analytics-plugin#153]
Recently, an SQL syntax error has been reported. On further investigation, it was found that the error occurs since there are some database columns named `value` and `value` is a reserved keyword. So we need to rename the `value` column to something else like `field_value`. Also see https://github.com/killbill/killbill-analytics-plugin/pull/151.

As part of this change, we will need to provide a migration file for the customers [here](https://github.com/killbill/killbill-analytics-plugin/tree/master/src/main/resources/migration).

We will also need to update the [database migration doc](https://docs.killbill.io/latest/database_migrations.html). See https://github.com/killbill/technical-support/issues/16.

**Comment by pierre** [comment]
Note that sending `/*! SET SQL_MODE=(SELECT CONCAT(@@SQL_MODE,',ANSI_QUOTES')) */;` as part of the query used to do the trick to allow `value` as a column name in the queries, but this does not always work anymore (e.g., on latest Aurora RDS).

**Comment by reshmabidikar** [comment]
Addressed in https://github.com/killbill/killbill-analytics-plugin/pull/154
