### ISSUE TITLE
Is this synchronized lock needed?

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-analytics-plugin#96]
There a [synchronized statement](https://github.com/killbill/killbill-analytics-plugin/blob/work-for-release-0.21.x/src/main/java/org/killbill/billing/plugin/analytics/dao/factory/BusinessContextFactory.java#L437) when fetching the catalog. Why is this needed?

From user report we see lots of threads waiting on this lock:

```
osgi-analytics-refresh-77" id=271 state=BLOCKED
    - waiting to lock <0x758459f0> (a org.killbill.billing.plugin.analytics.dao.factory.BusinessContextFactory)
     owned by analytics_notifications-th id=296
    at org.killbill.billing.plugin.analytics.dao.factory.BusinessContextFactory.getCatalog(BusinessContextFactory.java:438)
...
```

**Comment by sbrossie** [comment]
With the default # `osgi-analytics-refresh` set to 100, we can easily see 85 threads blocked on this statement!



```

**Comment by pierre** [comment]
It is needed to protect the cache instance variable but we can indeed do better: https://github.com/killbill/killbill-analytics-plugin/pull/97.
